config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tests#index"

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update gist] do
    get :result, on: :member
  end

  resources :gists, only: :create

  resources :badges, only: :index

  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  validates :name, :image, :rule, presence: true

  RULES = {
    "Passing all tests from the category" => :all_category_of_tests_passed,
    "Passing the test on the first try" => :first_attempt,
    "Passing all tests of a certain level" => :level_tests_passed
  }.freeze
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path, notice: t(".success")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: t(".update")
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t(".destroy")
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image, :rule, :rule_parametr)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/edit.html.erb
<h1>Edit badge</h1>

<%= form_with model: @badge, url: admin_badges_path, local: true do |form| %>
<%= render "shared/errors", resource: @badge %>
  <div>
    <%= form.label :name, "Name" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, "Image" %>
    <%= form.text_field :image %>
  </div>

 <div>
    <%= form.label :rule, "Rule" %>
    <%= form.select :rule, Badge::RULES.map { |rule| rule }, { prompt: "Select rule" } %>
  </div>

  <div>
  <%= form.label :rule_parametr, "Rule parametr" %>
  <%= form.text_field :rule_parametr %>
  </div>

  <%= form.submit "Edit badge", class: 'btn btn-primary' %>
<% end %>

app/views/admin/badges/index.html.erb
<h1><% t(".header") %></h1>

<p>
  <%= link_to t(".new"), new_admin_badge_path %>
</p>

<table class="table">
  <tr>
    <th><%= t(".name") %></th>
    <th><%= t(".image") %></th>
    <th><%= t(".rule") %></th>
    <th><%= t(".rule_parametr") %></th>
    <th colspan="3"><%= t(".actions") %></th>
  </tr>
<tbody>
  <% @badges.each do |badge| %>
    <tr>
      <td><%= badge.name %></td>
      <td><img src="<%= badge.image %>" alt="<%= badge.name %>" width="40"></td>
      <td><%= badge.rule %></td>
      <td><%= badge.rule_parametr %></td>
      <td>
        <%= link_to t(".edit"), edit_admin_badge_path(badge), class: "btn btn-primary" %>
        <%= link_to t(".delete"), admin_badge_path(badge),
                    method: :delete,
                    data: { confirm: "Are you sure?" },
                    class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/admin/badges/new.html.erb
<h1>New badge</h1>

<%= form_with model: @badge, url: admin_badges_path, local: true do |form| %>
<%= render "shared/errors", resource: @badge %>
  <div>
    <%= form.label :name, "Name" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, "Image" %>
    <%= form.text_field :image %>
  </div>

 <div>
    <%= form.label :rule, "Rule" %>
    <%= form.select :rule, Badge::RULES.map { |rule| rule }, { prompt: "Select rule" } %>
  </div>

  <div>
  <%= form.label :rule_parametr, "Rule parametr" %>
  <%= form.text_field :rule_parametr %>
  </div>

  <%= form.submit "Create badge", class: 'btn btn-primary' %>
<% end %>