config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tests#index"

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update gist] do
    get :result, on: :member
  end

  resources :gists, only: :create

  resources :badges, only: :index

  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :test
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, only: %i[create update]

  before_update :set_successful, if: :complited?

  SUCCESS_RATE = 85

  def complited?
    current_question.nil?
  end

  def accept!(answer_ids)
    if answer_ids.blank?
      errors.add(:base, "Please, select answer.")
      return false
    end
    if correct_answer?(answer_ids)
      self.correct_quesstions += 1
    end
    save!
  end

  def test_passed?
    (correct_quesstions.to_f / test.questions.count * 100).round(2) >= SUCCESS_RATE
  end

  def number_of_question
    (self.test.questions.index(current_question) + 1).to_f / test.questions.count
  end

  def remaining_time
    end_time = created_at + test.timer.minutes
    [0, (end_time - Time.current).to_i].max
  end

  def times_out?
    remaining_time <= 0
  end

  private

  def before_validation_set_question
    if test.present? && test.questions.any?
      self.current_question = test.questions.first if current_question.nil?
    else
      errors.add(:base, "Sorry, this test has no questions yet.")
    end
  end

  def correct_answer?(answer_ids)
    !answer_ids.nil? && correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_successful
    self.successful = test_passed?
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :set_test_passage, only: %i[show result update]

  def show
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.complited?
      BadgeService.new(current_user,@test_passage).call
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    elsif @test_passage.times_out?
      if @test_passage.complited?
        BadgeService.new(current_user,@test_passage).call
        TestsMailer.completed_test(@test_passage).deliver_now
        redirect_to result_test_passage_path(@test_passage)
      else
        flash.now[:alert] = "Time is out!"
        redirect_to test_passage_path(@test_passage)
      end
    else
      flash.now[:alert] = @test_passage.errors.full_messages.to_sentence
      redirect_to test_passage_path
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
    if @test_passage.test.questions.empty?
      flash[:alert] = "Sorry, this test has no questions yet."
      redirect_to tests_path
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1>The <%= @test_passage.test.title %>Test was Completed!</h1>

<p>
  <% if @test_passage.test_passed? %>
    <span style="color: green;">The test was successfully passed!</span>
  <% else %>
    <span style="color: red;">Test failed!</span>
  <% end %>
</p>

<%= link_to 'Back to all tests', 'tests_path' %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %>Test</h1>

<b>
  <%= @test_passage.current_question.body %>
</b>

<%= content_tag :div,
              class: 'progress',
              data: { questions_completed: @test_passage.test.questions.index(@test_passage.current_question) + 1,
                      number_of_questions: @test_passage.test.questions.count
              } do %>
  <div class="progress-bar progress-bar-striped" role="progressbar"></div>
<% end %>

<span id="time-left"
      data-end-time="<%= Time.current.to_i + @test_passage.remaining_time %>"
      data-redirect-url="<%= result_test_passage_path(@test_passage) %>">
  <%= @test_passage.remaining_time %> <%= t(".left") %>
</span>

<%= form_with url: test_passage_path(@test_passage),
              local: true,
              class: "testFrom",
              method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box %>
      <%= b.label %>
    </p>
    <% end %>
  <p><%= @test_passage.number_of_question %></p>

  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <p><%= link_to 'Gist Question', gists_path(test_passage: @test_passage), method: :post %></p>


  <p><%= form.submit 'Next' %></p>
  <% end %>