config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tests#index"

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update gist] do
    get :result, on: :member
  end

  resources :gists, only: :create

  resources :badges, only: :index

  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_4_answers, on: :create

  scope :correct, -> { where(correct: true) }

  def validate_4_answers
    if question.answers.size > 4
      errors.add(:question, "should have between 1 and 4 answers") if question.answers.count > 4
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer], notice: 'Answer was successfully created!'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question]
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %>
  <%= link_to t('show'), admin_answer_path(answer) %>
  <%= link_to t('edit'), edit_admin_answer_path(answer) %>

  <%= link_to t('delete'),
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: 'Are you sure?'} %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer] do |form| %>
<%= render 'shared/errors', resource: @answer%>

<p>
  <%= form.label :body %>
  <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
</p>

<p>
  <%= form.label :correct %>
  <%= form.check_box :correct, id: :answer_correct %>
</p>

   <p><%= form.submit %></p>
 <% end %>

app/views/admin/answers/edit.html.erb
<h1>Edit answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>
<%= link_to t('back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New answer for question: "<%=@question.body%>"</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to t("back"), admin_question_path(@answer.question) %>
</div>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to t("back"), admin_question_path(@answer.question) %>